export const nftMarketAbi = [{
	"inputs": [{
		"internalType": "address",
		"name": "_paymentTokenAddress",
		"type": "address"
	}],
	"stateMutability": "nonpayable",
	"type": "constructor"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "uint256",
		"name": "listingId",
		"type": "uint256"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "seller",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "nftContract",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "price",
		"type": "uint256"
	}],
	"name": "NFTListed",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "uint256",
		"name": "listingId",
		"type": "uint256"
	}],
	"name": "NFTListingCancelled",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "uint256",
		"name": "listingId",
		"type": "uint256"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "buyer",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "seller",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "address",
		"name": "nftContract",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "price",
		"type": "uint256"
	}],
	"name": "NFTSold",
	"type": "event"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "_listingId",
		"type": "uint256"
	}],
	"name": "buyNft",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "_listingId",
		"type": "uint256"
	}],
	"name": "cancelListing",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_nftContract",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "_tokenId",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "_price",
		"type": "uint256"
	}],
	"name": "list",
	"outputs": [{
		"internalType": "uint256",
		"name": "s",
		"type": "uint256"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"name": "listings",
	"outputs": [{
		"internalType": "address",
		"name": "seller",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "nftContract",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "tokenId",
		"type": "uint256"
	}, {
		"internalType": "uint256",
		"name": "price",
		"type": "uint256"
	}, {
		"internalType": "bool",
		"name": "isActive",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "nextListingId",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "paymentToken",
	"outputs": [{
		"internalType": "contract MyERC20",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}]